export * from './classes';
export * from './enums';
export * from './interfaces';
export * from './structs';

export const inheritanceMap = {
  'UFGAISystem': ["Unknown<'UAISystem'>", "Unknown<'FTickableGameObject'>"],
  'UFGAttack': ['UObject'],
  'UFGAttackCustomRadial': ['UFGAttack'],
  'UFGAttackMelee': ['UFGAttack'],
  'UFGAttackMeleeJump': ['UFGAttackMelee'],
  'UFGAttackRanged': ['UFGAttack'],
  'AFGCreatureController': ["Unknown<'AAIController'>"],
  'AFGEnemyController': ['AFGCreatureController'],
  'UFGEnvQueryGenerator_ForAngle': ["Unknown<'UEnvQueryGenerator_ProjectedPoints'>"],
  'UFGEnvQueryTest_ItemDescription': ["Unknown<'UEnvQueryTest'>"],
  'UFGNavArea_Factory': ["Unknown<'UNavArea'>"],
  'UFGNavArea_HardNature': ["Unknown<'UNavArea'>"],
  'UFGNavArea_Water': ["Unknown<'UNavArea'>"],
  'UFGAvailabilityDependency': ['UObject'],
  'UFGItemPickedUpDependency': ['UFGAvailabilityDependency'],
  'UFGFAnimInstanceFactory': ["Unknown<'UAnimInstance'>"],
  'AFGBuildable': [
    'AActor',
    'IFGDismantleInterface',
    'IFGSaveInterface',
    'IFGColorInterface',
    'IFGUseableInterface',
  ],
  'AFGBuildableAttachmentMerger': ['AFGBuildableConveyorAttachment'],
  'AFGBuildableAttachmentSplitter': ['AFGBuildableConveyorAttachment'],
  'AFGBuildableAutomatedWorkBench': ['AFGBuildableManufacturer'],
  'AFGBuildableCheatFluidSink': ['AFGBuildableFactory', 'IFGFluidIntegrantInterface'],
  'AFGBuildableCheatFluidSpawner': ['AFGBuildableFactory', 'IFGFluidIntegrantInterface'],
  'AFGBuildableConverter': ['AFGBuildableManufacturer'],
  'AFGBuildableConveyorAttachment': ['AFGBuildableFactory'],
  'UFGConveyorRemoteCallObject': ['UFGRemoteCallObject'],
  'UPresistentConveyorPackagingData': ['UObject'],
  'AFGBuildableConveyorBase': ['AFGBuildable', 'IFGSignificanceInterface'],
  'UFGUseState_ConveyorBeltValid': ['UFGUseState'],
  'UFGUseState_ConveyorBeltFullInventory': ['UFGUseState'],
  'UFGUseState_ConveyorBeltEmpty': ['UFGUseState'],
  'AFGBuildableConveyorBelt': ['AFGBuildableConveyorBase'],
  'AFGBuildableConveyorLift': ['AFGBuildableConveyorBase'],
  'AFGBuildableDecor': ['AFGBuildable'],
  'AFGBuildableDockingStation': ['AFGBuildableFactory'],
  'AFGBuildableFactory': [
    'AFGBuildable',
    'IFGSignificanceInterface',
    'IFGReplicationDetailActorOwnerInterface',
  ],
  'AFGBuildableFactoryBuilding': ['AFGBuildable'],
  'AFGBuildableFoundation': ['AFGBuildableFactoryBuilding'],
  'AFGBuildableGenerator': ['AFGBuildableFactory'],
  'AFGBuildableGeneratorFuel': ['AFGBuildableGenerator'],
  'AFGBuildableGeneratorGeoThermal': ['AFGBuildableGenerator'],
  'AFGBuildableGeneratorNuclear': ['AFGBuildableGeneratorFuel'],
  'AFGBuildableHubTerminal': ['AFGBuildable'],
  'AFGBuildableManufacturer': ['AFGBuildableFactory', 'IFGRecipeProducerInterface'],
  'AFGBuildablePipeBase': ['AFGBuildable', 'IFGSignificanceInterface'],
  'AFGBuildablePipeHyper': ['AFGBuildablePipeBase', 'IFGPipeHyperInterface'],
  'AFGBuildablePipeline': ['AFGBuildablePipeBase', 'IFGFluidIntegrantInterface'],
  'AFGBuildablePipelineAttachment': ['AFGBuildableFactory', 'IFGFluidIntegrantInterface'],
  'AFGBuildablePipelineJunction': ['AFGBuildablePipelineAttachment'],
  'AFGBuildablePipelinePump': ['AFGBuildablePipelineAttachment'],
  'AFGBuildablePipeReservoir': ['AFGBuildableFactory', 'IFGFluidIntegrantInterface'],
  'AFGBuildablePole': ['AFGBuildablePoleBase'],
  'AFGBuildablePoleBase': ['AFGBuildable'],
  'AFGBuildablePoweredWall': ['AFGBuildableWall'],
  'AFGBuildablePowerPole': ['AFGBuildable'],
  'AFGBuildableRadarTower': ['AFGBuildableFactory'],
  'AFGBuildableRailroadBridge': ['AFGBuildable'],
  'AFGBuildableRailroadSignal': ['AFGBuildable'],
  'AFGBuildableRailroadStation': ['AFGBuildableTrainPlatform'],
  'AFGBuildableRailroadSwitchControl': ['AFGBuildableFactory'],
  'AFGBuildableRailroadTrack': ['AFGBuildable'],
  'AFGBuildableRamp': ['AFGBuildableFoundation'],
  'AFGBuildableResourceExtractor': ['AFGBuildableFactory'],
  'AFGBuildableResourceSink': ['AFGBuildableFactory'],
  'AFGBuildableResourceSinkShop': ['AFGBuildableFactory'],
  'AFGBuildableRoad': ['AFGBuildable'],
  'AFGBuildableSignWall': ['AFGBuildableWall'],
  'AFGBuildableSpaceElevator': ['AFGBuildableFactory'],
  'AFGBuildableSpeedSign': ['AFGBuildable'],
  'AFGBuildableSplitterSmart': ['AFGBuildableAttachmentSplitter'],
  'AFGBuildableStair': ['AFGBuildableFoundation'],
  'AFGBuildableStandaloneSign': ['AFGBuildable', 'IFGSignInterface', 'IFGSignificanceInterface'],
  'AFGBuildableStorage': ['AFGBuildableFactory'],
  'AFGBuildableTradingPost': ['AFGBuildableFactory'],
  'AFGBuildableTrainPlatform': ['AFGBuildableFactory'],
  'AFGBuildableTrainPlatformCargo': ['AFGBuildableTrainPlatform'],
  'AFGBuildableTrainPlatformEmpty': ['AFGBuildableTrainPlatform'],
  'AFGBuildableWalkway': ['AFGBuildableFactoryBuilding'],
  'AFGBuildableWall': ['AFGBuildableFactoryBuilding'],
  'AFGBuildableWindTurbine': ['AFGBuildableFactory'],
  'AFGBuildableWire': ['AFGBuildable'],
  'AFGCentralStorageContainer': ['AFGBuildableStorage'],
  'AFGConveyorPoleStackable': ['AFGBuildablePole'],
  'AFGPipeHyperStart': ['AFGBuildablePipeHyperPart'],
  'AFGCrabHatcher': ['AFGEnemy'],
  'AFGEnemy': ['AFGCreature'],
  'UFGameplayTaskResource_Attack': ["Unknown<'UGameplayTaskResource'>"],
  'UFGGameplayTask_Attack': ['UFGGameplayTask_Base'],
  'UFGGameplayTask_AttackJump': ['UFGGameplayTask_Attack'],
  'UFGGameplayTask_AttackMelee': ['UFGGameplayTask_Attack'],
  'UFGGameplayTask_Base': ["Unknown<'UGameplayTask'>"],
  'AFGCreature': ['AFGCharacterBase'],
  'AFGCreatureSeat': ['AFGDriveablePawn'],
  'AFGCreatureSpawner': ['AActor', 'IFGSaveInterface'],
  'UFGCreatureSpawnerDebugComponent': ["Unknown<'UActorComponent'>"],
  'UFGLootSettings': ['UObject'],
  'UFGDamageType': ["Unknown<'UDamageType'>"],
  'UFGBuildGunState': ['UObject'],
  'AFGBuildGun': ['AFGEquipment', 'IFGRecipeProducerInterface'],
  'AFGBuildGunAttachment': ['AFGEquipmentAttachment'],
  'UFGBuildGunStateBuild': ['UFGBuildGunState'],
  'UFGBuildGunStateDismantle': ['UFGBuildGunState'],
  'AFGC4Dispenser': ['AFGWeapon'],
  'AFGChainsaw': ['AFGEquipment'],
  'AFGConsumableEquipment': ['AFGEquipment'],
  'AFGDowsingStick': ['AFGEquipment'],
  'AFGDowsingStickAttachment': ['AFGEquipmentAttachment'],
  'AFGEquipment': ['AActor', 'IFGSaveInterface', 'IFGReplicationDependencyActorInterface'],
  'AFGEquipmentAttachment': ['AActor'],
  'AFGEquipmentDecoration': ['AFGEquipment'],
  'AFGEquipmentStunSpear': ['AFGEquipment'],
  'AFGGasMask': ['AFGEquipment'],
  'AFGGasMaskAttachment': ['AFGEquipmentAttachment'],
  'AFGGolfCartDispenser': ['AFGEquipment'],
  'AFGHookshot': ['AFGEquipment'],
  'AFGJetPack': ['AFGEquipment'],
  'AFGJetPackAttachment': ['AFGEquipmentAttachment'],
  'AFGObjectScanner': ['AFGEquipment'],
  'AFGObjectScannerAttachment': ['AFGEquipmentAttachment'],
  'UFGParachuteCameraShake': ["Unknown<'UCameraShake'>"],
  'AFGParachute': ['AFGEquipment'],
  'AFGParachuteAttachment': ['AFGEquipmentAttachment'],
  'AFGPortableMinerDispenser': ['AFGEquipment'],
  'AFGResourceMiner': ['AFGEquipment'],
  'AFGResourceScanner': ['AFGEquipment'],
  'AFGSuitBase': ['AFGEquipment'],
  'AFGSuitBaseAttachment': ['AFGEquipmentAttachment'],
  'AFGToolBelt': ['AFGEquipment'],
  'AFGWeapon': ['AFGEquipment'],
  'AFGWeaponAttachment': ['AFGEquipmentAttachment'],
  'AFGWeaponInstantFire': ['AFGWeapon'],
  'AFGWeaponProjectileFire': ['AFGWeapon'],
  'UFGActorRepresentation': ['UObject'],
  'AFGActorRepresentationManager': ['AFGSubsystem'],
  'AFGAdminInterface': ["Unknown<'AInfo'>"],
  'UFGAmbientSettings': ['UObject'],
  'AFGAmbientSoundSpline': ['AActor', 'IFGSignificanceInterface'],
  'AFGAmbientVolume': ["Unknown<'AVolume'>", 'IFGSignificanceInterface'],
  'UFGAnimNotify_Attack': ["Unknown<'UAnimNotify'>"],
  'UFGAnimNotify_FootDown': ["Unknown<'UAnimNotify'>"],
  'UFGAnimNotify_Landed': ["Unknown<'UAnimNotify'>"],
  'UFGAnimPlayer': ['UFGCharacterAnimInstance'],
  'UFGAssetManager': ["Unknown<'UAssetManager'>"],
  'UFGAtmosphereUpdater': ['UObject'],
  'AFGAtmosphereVolume': [
    "Unknown<'AVolume'>",
    "Unknown<'ICurvePanningInterface'>",
    "Unknown<'IInterface_PostProcessVolume'>",
  ],
  'AFGAttentionPingActor': ['AActor'],
  'AFGAudioVolumeSubsystem': ['AFGSubsystem'],
  'AFGBeacon': ['AActor'],
  'UFGBlueprintFunctionLibrary': ["Unknown<'UBlueprintFunctionLibrary'>"],
  'UFGBoundedTextRenderComponent': ['TextRenderComponent'],
  'AFGBuildablePipelineSupport': ['AFGBuildablePoleBase'],
  'AFGBuildablePipePart': ['AFGBuildableFactory'],
  'AFGBuildablePipeHyperPart': ['AFGBuildablePipePart', 'IFGPipeHyperInterface'],
  'AFGBuildableSubsystem': ['AFGSubsystem', 'IFGSaveInterface'],
  'UFGBuildCategory': ['UObject'],
  'AFGBuildEffectSpline': ['AActor'],
  'UFGBuildSubCategory': ['UFGBuildCategory'],
  'AFGC4Explosive': ['AActor'],
  'UFGCameraModifierLimitLook': ["Unknown<'UCameraModifier'>"],
  'UFGCameraModifierSlide': ["Unknown<'UCameraModifier'>"],
  'AFGCentralStorageSubsystem': ['AFGSubsystem'],
  'UFGCharacterAnimInstance': ["Unknown<'UAnimInstance'>"],
  'AFGCharacterBase': ["Unknown<'ACharacter'>", 'IFGSaveInterface'],
  'UFGCharacterMovementComponent': ["Unknown<'UCharacterMovementComponent'>"],
  'UFGUseState_ReviveInvalid_PlayerNotDead': ['UFGUseState'],
  'UFGUseState_ReviveValid': ['UFGUseState'],
  'AFGCharacterPlayer': [
    'AFGCharacterBase',
    'IFGAggroTargetInterface',
    'IFGUseableInterface',
    'IFGRadiationInterface',
  ],
  'AFGChatManager': ['AFGSubsystem'],
  'UFGCheatManager': ["Unknown<'UCheatManager'>"],
  'UFGCircuit': ['UObject', 'IFGSaveInterface'],
  'UFGCircuitConnectionComponent': ['UFGConnectionComponent'],
  'AFGCircuitSubsystem': ['AFGSubsystem', 'IFGSaveInterface'],
  'UFGColoredInstanceManager': ["Unknown<'USceneComponent'>"],
  'UFGColoredInstanceMeshProxy': ["Unknown<'UStaticMeshComponent'>"],
  'AFGColorGun': ['AFGWeaponInstantFire'],
  'UFGCombatFunctionLibrary': ["Unknown<'UBlueprintFunctionLibrary'>"],
  'UFGConnectionComponent': ["Unknown<'USceneComponent'>", 'IFGSaveInterface'],
  'UFGConsoleCommandManager': ['UObject'],
  'UFGConstructDisqualifier': ['UObject'],
  'UFGCDInitializing': ['UFGConstructDisqualifier'],
  'UFGCDInvalidAimLocation': ['UFGConstructDisqualifier'],
  'UFGCDUnaffordable': ['UFGConstructDisqualifier'],
  'UFGCDInvalidPlacement': ['UFGConstructDisqualifier'],
  'UFGCDEncroachingClearance': ['UFGConstructDisqualifier'],
  'UFGCDEncroachingPlayer': ['UFGConstructDisqualifier'],
  'UFGCDInvalidFloor': ['UFGConstructDisqualifier'],
  'UFGCDUniqueBuilding': ['UFGConstructDisqualifier'],
  'UFGCDMustSnap': ['UFGConstructDisqualifier'],
  'UFGCDShouldntSnap': ['UFGConstructDisqualifier'],
  'UFGCDNeedsResourceNode': ['UFGConstructDisqualifier'],
  'UFGCDResourceNodeIsOccuped': ['UFGConstructDisqualifier'],
  'UFGCDResourceIsTooShallow': ['UFGConstructDisqualifier'],
  'UFGCDNeedsWaterVolume': ['UFGConstructDisqualifier'],
  'UFGCDResourceDeposit': ['UFGConstructDisqualifier'],
  'UFGCDWireSnap': ['UFGConstructDisqualifier'],
  'UFGCDWireTooLong': ['UFGConstructDisqualifier'],
  'UFGCDWireTooManyConnections': ['UFGConstructDisqualifier'],
  'UFGCDBeltMustSnap': ['UFGConstructDisqualifier'],
  'UFGCDConveyorTooLong': ['UFGConstructDisqualifier'],
  'UFGCDConveyorTooShort': ['UFGConstructDisqualifier'],
  'UFGCDConveyorTooSteep': ['UFGConstructDisqualifier'],
  'UFGCDConveyorInvalidShape': ['UFGConstructDisqualifier'],
  'UFGCDConveyorAttachmentTooSharpTurn': ['UFGConstructDisqualifier'],
  'UFGCDMustHaveRailRoadTrack': ['UFGConstructDisqualifier'],
  'UFGCDMustAttachToTrainPlatform': ['UFGConstructDisqualifier'],
  'UFGCDTrackTooLong': ['UFGConstructDisqualifier'],
  'UFGCDTrackTooShort': ['UFGConstructDisqualifier'],
  'UFGCDTrackTooSteep': ['UFGConstructDisqualifier'],
  'UFGCDTrackTrunToSharp': ['UFGConstructDisqualifier'],
  'UFGCDPipeTooShort': ['UFGConstructDisqualifier'],
  'UFGCDPipeTooLong': ['UFGConstructDisqualifier'],
  'UFGCDPipeAttachmentTooSharpTurn': ['UFGConstructDisqualifier'],
  'UFGCDPipeMustSnap': ['UFGConstructDisqualifier'],
  'UFGCDPipeFluidTypeMismatch': ['UFGConstructDisqualifier'],
  'UFGCDPipeInvalidShape': ['UFGConstructDisqualifier'],
  'UFGCDPipeNoPathFound': ['UFGConstructDisqualifier'],
  'AFGCrashSiteDebris': ['AActor'],
  'AFGCrashSiteDebrisActor': ['AActor', 'IFGSignificanceInterface'],
  'AFGCrate': ['AFGInteractActor', 'IFGSaveInterface'],
  'UFGDamageOverTime': ['UObject'],
  'AFGDamageOverTimeVolume': ["Unknown<'AVolume'>", "Unknown<'IInterface_PostProcessVolume'>"],
  'AFGDecorationActor': ['AFGInteractActor', 'IFGSaveInterface'],
  'AFGDestructibleActor': ["Unknown<'ADestructibleActor'>", 'IFGSaveInterface'],
  'AFGDestructiveProjectile': ['AFGProjectile'],
  'UFGDotComponent': ["Unknown<'USceneComponent'>"],
  'AFGDriveablePawn': ["Unknown<'APawn'>", 'IFGSaveInterface'],
  'AFGDropPod': ['AActor', 'IFGUseableInterface', 'IFGSaveInterface', 'IFGSignificanceInterface'],
  'UFGDropPodSettings': ['UFGSettings'],
  'UFGEnvironmentSettings': ['UFGSettings'],
  'AFGEquipmentChild': ['AActor'],
  'UFGErrorMessage': ['UObject'],
  'UFGFactoryConnectionComponent': ['UFGConnectionComponent'],
  'UFGFactoryLegsComponent': ["Unknown<'USceneComponent'>", 'IFGSaveInterface'],
  'UFGFactoryMaterialInstanceManager': ['UObject'],
  'UFGFactorySettings': ['UFGSettings'],
  'AFGFluffActor': ['AActor'],
  'UFGFoliageIdentifier': ['UObject'],
  'UFGFoliageIdentifier_RemovableByBuildings': ['UFGFoliageIdentifier'],
  'UFGFoliageIdentifier_Pickupable': ['UFGFoliageIdentifier_RemovableByBuildings'],
  'UFGFoliageIdentifier_Chainsawable': ['UFGFoliageIdentifier'],
  'UFGFoliageIdentifier_ChainsawableXmasTree': ['UFGFoliageIdentifier_Chainsawable'],
  'UFGFoliageIdentifier_VehicleDestroyable': ['UFGFoliageIdentifier'],
  'UFGFoliageIdentifier_ExplosiveDestroyable': ['UFGFoliageIdentifier'],
  'UFGFoliageLibrary': ['UObject'],
  'AFGFoliagePickup': ['AActor', 'IFGUseableInterface'],
  'AFGFoliageRemoval': ['AActor', 'IFGSaveInterface'],
  'AFGFoliageRemovalSubsystem': ['AFGSubsystem'],
  'UFGFoliageResourceUserData': ["Unknown<'UAssetUserData'>"],
  'AFGFoundationSubsystem': ['AFGSubsystem', 'IFGSaveInterface'],
  'AFGFreightWagon': ['AFGRailroadVehicle'],
  'UFGGameEngine': ["Unknown<'UGameEngine'>", 'IFGWorldCreationInterface'],
  'UFGGameInstance': ["Unknown<'UGameInstance'>"],
  'AFGGameMode': ["Unknown<'AGameMode'>", 'IFGSaveInterface'],
  'AFGGamePhaseManager': ['AFGSubsystem', 'IFGSaveInterface'],
  'AFGGameSession': ["Unknown<'AGameSession'>"],
  'AFGGameState': ["Unknown<'AGameState'>", 'IFGSaveInterface'],
  'UFGGameUserSettings': ["Unknown<'UGameUserSettings'>"],
  'UFGGameViewportClient': ["Unknown<'UGameViewportClient'>"],
  'AFGGasPillar': ['AActor', 'IFGSignificanceInterface', "Unknown<'IInterface_PostProcessVolume'>"],
  'UFGGlobalSettings': ['UObject'],
  'UFGHardDriveSettings': ['UFGSettings'],
  'UFGHealthComponent': ["Unknown<'UActorComponent'>", 'IFGSaveInterface'],
  'UFGHotbarShortcut': ['UObject', 'IFGSaveInterface'],
  'AFGHUD': ['AFGHUDBase'],
  'AFGHUDBase': ["Unknown<'AHUD'>"],
  'UFGInputLibrary': ["Unknown<'UBlueprintFunctionLibrary'>"],
  'AFGInteractableMarker': ['AActor'],
  'AFGInteractActor': ['AActor', 'IFGUseableInterface'],
  'UFGInventoryComponent': ["Unknown<'UActorComponent'>", 'IFGSaveInterface'],
  'UFGInventoryComponentBeltSlot': ['UFGInventoryComponent'],
  'UFGInventoryComponentEquipment': ['UFGInventoryComponent'],
  'UFGInventoryComponentTrash': ['UFGInventoryComponent'],
  'UFGInventoryLibrary': ["Unknown<'UBlueprintFunctionLibrary'>"],
  'UFGItemCategory': ['UObject'],
  'AFGItemPickup_Spawnable': ['AFGItemPickup'],
  'UFGUseState_FullInventory': ['UFGUseState'],
  'UFGUseState_Collecting': ['UFGUseState'],
  'AFGItemPickup': ['AActor', 'IFGUseableInterface', 'IFGSaveInterface', 'IFGSignificanceInterface'],
  'AFGJumpingStilts': ['AFGEquipment'],
  'AFGJumpingStiltsAttachment': ['AFGEquipmentAttachment'],
  'UFGLadderComponent': ["Unknown<'UBoxComponent'>"],
  'UFGEM_LoggedOutFromOnlineService': ['UFGErrorMessage'],
  'UFGEM_LostConnectionWithOnlineService': ['UFGErrorMessage'],
  'UFGEM_FailedToLoginToOnlineService': ['UFGErrorMessage'],
  'UFGLocalPlayer': ["Unknown<'ULocalPlayer'>"],
  'AFGLocomotive': ['AFGRailroadVehicle'],
  'UFGLocomotiveMovementComponent': ['UFGRailroadVehicleMovementComponent'],
  'AFGManta': ['AActor', 'IFGSignificanceInterface'],
  'UFGMapArea': ['UObject'],
  'UFGMapAreaTexture': ['UObject'],
  'UFGMapAreaZoneDescriptor': ['UObject'],
  'UFGMapCompassSettings': ["Unknown<'UDeveloperSettings'>"],
  'UFGMapFunctionLibrary': ["Unknown<'UBlueprintFunctionLibrary'>"],
  'AFGMapManager': ['AFGSubsystem', 'IFGSaveInterface'],
  'UFGMaterialEffect_Build': ['UFGMaterialEffectComponent'],
  'UFGMaterialEffectComponent': ["Unknown<'UActorComponent'>"],
  'UFGMaterialFlowAnalysisFunctionLibrary': ["Unknown<'UBlueprintFunctionLibrary'>"],
  'UFGHeightWaterUserData': ["Unknown<'UAssetUserData'>"],
  'UFGHeightFoliageUserData': ["Unknown<'UAssetUserData'>"],
  'UFGHeightHideUserData': ["Unknown<'UAssetUserData'>"],
  'AFGMinimapCaptureActor': ["Unknown<'ASceneCapture2D'>"],
  'UFGMusicManager': ['UObject'],
  'UFGPresenceLibrary': ["Unknown<'UBlueprintFunctionLibrary'>"],
  'UFGFriendsLibrary': ["Unknown<'UBlueprintFunctionLibrary'>"],
  'UFGSessionLibrary': ["Unknown<'UBlueprintFunctionLibrary'>"],
  'UFGInviteLibrary': ["Unknown<'UBlueprintFunctionLibrary'>"],
  'UFGNetworkLibrary': ["Unknown<'UBlueprintFunctionLibrary'>"],
  'AFGNewsFeedActor': ['AActor'],
  'AFGNobeliskDetonator': ['AFGWeapon'],
  'AFGNobeliskDetonatorAttachment': ['AFGWeaponAttachment'],
  'AFGNobeliskExplosive': ['AFGDestructiveProjectile'],
  'AFGNobeliskExplosiveAttachment': ['AFGWeaponAttachment'],
  'UFGOnlineSessionClient': ["Unknown<'UOnlineSessionClient'>"],
  'UFGOptionsLibrary': ["Unknown<'UBlueprintFunctionLibrary'>"],
  'UFGOptionsSettings': ["Unknown<'UDeveloperSettings'>"],
  'UFGOutlineComponent': ["Unknown<'USceneComponent'>"],
  'AFGPassengerSeat': ['AFGDriveablePawn'],
  'AFGPipeBuilder': ['AFGVehicle'],
  'AFGPipeBuilderTrail': ['AActor'],
  'UFGPipeConnectionComponentBase': ['UFGConnectionComponent'],
  'UFGPipeConnectionComponent': ['UFGPipeConnectionComponentBase'],
  'UFGPipeConnectionFactory': ['UFGPipeConnectionComponent', 'IFGFluidIntegrantInterface'],
  'UFGPipelineFlowIndicatorComponent': ["Unknown<'UStaticMeshComponent'>"],
  'AFGPipeNetwork': ["Unknown<'AInfo'>", 'IFGSaveInterface'],
  'AFGPipeSubsystem': ['AFGSubsystem', 'IFGSaveInterface'],
  'AFGPlanet': ['AActor'],
  'AFGPlayerController': ['AFGPlayerControllerBase'],
  'AFGPlayerControllerBase': ["Unknown<'APlayerController'>"],
  'UFGPlayerSettings': ["Unknown<'UDeveloperSettings'>"],
  'AFGPlayerStartTradingPost': ["Unknown<'APlayerStart'>"],
  'AFGPlayerState': ["Unknown<'APlayerState'>", 'IFGSaveInterface'],
  'UFGPopupWidgetContent': ["Unknown<'UUserWidget'>"],
  'AFGPortableMiner': ['AActor', 'IFGUseableInterface', 'IFGSaveInterface'],
  'UFGPowerCircuit': ['UFGCircuit'],
  'UFGPowerCircuitWidget': ["Unknown<'UUserWidget'>"],
  'UFGPowerConnectionComponent': ['UFGCircuitConnectionComponent'],
  'UFGPowerInfoComponent': ["Unknown<'UActorComponent'>", 'IFGSaveInterface'],
  'AFGProceduralStaticMeshActor': ["Unknown<'AStaticMeshActor'>"],
  'UFGProductionIndicatorComponent': ["Unknown<'UActorComponent'>"],
  'UFGProductionIndicatorInstanceComponent': ["Unknown<'UStaticMeshComponent'>"],
  'UFGProductionIndicatorInstanceManager': ["Unknown<'USceneComponent'>"],
  'AFGProjectile': ['AActor', 'IFGSaveInterface'],
  'AFGProximitySubsystem': ['AActor'],
  'UFGRadiationSettings': ["Unknown<'UDeveloperSettings'>"],
  'AFGRadioactiveActor': ['AActor'],
  'AFGRadioactivitySubsystem': ['AFGSubsystem'],
  'UFGRailroadFunctionLibrary': ["Unknown<'UBlueprintFunctionLibrary'>"],
  'AFGRailroadSubsystem': ['AFGSubsystem', 'IFGSaveInterface'],
  'AFGRailroadTimeTable': ["Unknown<'AInfo'>", 'IFGSaveInterface'],
  'UFGRailroadTrackConnectionComponent': ['UFGConnectionComponent'],
  'AFGRailroadVehicle': ['AFGVehicle'],
  'UFGRailRoadVehicleAnim': ["Unknown<'UAnimInstance'>"],
  'UFGRailroadVehicleMovementComponent': ["Unknown<'UPawnMovementComponent'>"],
  'UFGRailroadVehicleSoundComponent': ["Unknown<'USceneComponent'>"],
  'UFGRecipe': ['UObject'],
  'AFGRecipeManager': ['AFGSubsystem', 'IFGSaveInterface'],
  'UFGRecipeShortcut': ['UFGHotbarShortcut'],
  'UFGRemoteCallObject': ['UObject'],
  'AFGRenderTargetStage': ['AActor'],
  'UFGResearchMachine': ["Unknown<'USceneComponent'>", 'IFGRecipeProducerInterface'],
  'AFGResearchManager': ['AFGSubsystem', 'IFGSaveInterface'],
  'UFGResearchRecipe': ['UFGRecipe'],
  'UFGResearchTree': ['UObject'],
  'UFGResearchTreeNode': ['UObject'],
  'AFGResourceNodeGeyser': ['AFGResourceNode'],
  'UFGResourceSettings': ['UFGSettings'],
  'UFGResourceSinkCreditDescriptor': ['UFGItemDescriptor'],
  'UFGResourceSinkSettings': ["Unknown<'UDeveloperSettings'>"],
  'AFGResourceSinkSubsystem': ['AFGSubsystem', 'IFGSaveInterface'],
  'AFGRiverSpline': ['AActor'],
  'UFGRoadConnectionComponent': ['UFGConnectionComponent'],
  'UFGSaveSession': ['UObject'],
  'UFGSaveSystem': ['UObject'],
  'UFGSchematic': ['UObject'],
  'UFGSchematicCategory': ['UObject'],
  'AFGSchematicManager': ['AFGSubsystem', 'IFGSaveInterface'],
  'UFGSettings': ['UObject'],
  'UFGSharedPostProcessSettings': ['UObject'],
  'UFGSignificanceManager': ["Unknown<'USignificanceManager'>"],
  'UFGSignLayer': ['UObject', 'IFGSaveInterface'],
  'UFGSignElementData': ['UObject', 'IFGSaveInterface'],
  'UFGSignPixelData': ['UFGSignElementData'],
  'UFGSignTextData': ['UFGSignElementData'],
  'UFGSignIconData': ['UFGSignElementData'],
  'UFGSignSettings': ['UFGSettings'],
  'AFGSkySphere': ['AActor', "Unknown<'ICurvePanningInterface'>"],
  'UFGSoundSplineComponent': ["Unknown<'UAkComponent'>"],
  'UFGSplineComponent': ["Unknown<'USplineComponent'>"],
  'UFGSplineMeshGenerationLibrary': ["Unknown<'UBlueprintFunctionLibrary'>"],
  'AFGSplinePath': ['AActor'],
  'AFGSporeFlower': [
    'AActor',
    'IFGSaveInterface',
    'IFGSignificanceInterface',
    'IFGExplosiveDestroyableInterface',
  ],
  'AFGStartingPod': ['AActor', 'IFGDismantleInterface'],
  'UFGStingerWidgetRewardData': ['UObject'],
  'AFGStorySubsystem': ['AFGSubsystem', 'IFGSaveInterface'],
  'AFGSubsystem': ["Unknown<'AInfo'>"],
  'UFGSubsystemClasses': ['UFGSettings'],
  'AFGTargetPoint': ['AActor', 'IFGSaveInterface'],
  'UFGTargetPointLinkedList': ['UObject', 'IFGSaveInterface'],
  'AFGTimeOfDaySubsystem': ['AFGSubsystem', 'IFGSaveInterface'],
  'AFGTrain': ['AActor', 'IFGSaveInterface', 'IFGSignificanceInterface'],
  'UFGTrainPlatformConnection': ['UFGConnectionComponent'],
  'AFGTrainStationIdentifier': ["Unknown<'AInfo'>", 'IFGSaveInterface'],
  'AFGTutorialIntroManager': ['AFGSubsystem', 'IFGSaveInterface'],
  'UFGTutorialSubsystem': ['UObject', 'IFGSaveInterface'],
  'UFGUISettings': ["Unknown<'UDeveloperSettings'>"],
  'AFGUnlockSubsystem': ['AFGSubsystem', 'IFGSaveInterface'],
  'UFGUseState': ['UObject'],
  'UFGUseState_Valid': ['UFGUseState'],
  'UFGUseState_VehicleHasDriver': ['UFGUseState'],
  'UFGUseState_VehicleInWater': ['UFGUseState'],
  'UFGUseState_VehicleOccupied': ['UFGUseState'],
  'AFGVehicle': [
    'AFGDriveablePawn',
    'IFGUseableInterface',
    'IFGDismantleInterface',
    'IFGAggroTargetInterface',
    'IFGDockableInterface',
    'IFGColorInterface',
    'IFGSignificanceInterface',
  ],
  'UFGVehicleCollisionBoxComponent': ["Unknown<'UBoxComponent'>"],
  'UFGVehicleWheel': ["Unknown<'UVehicleWheel'>"],
  'UFGVersionFunctionLibrary': ["Unknown<'UBlueprintFunctionLibrary'>"],
  'AFGVolumeMapArea': ["Unknown<'AVolume'>"],
  'UFGWaterAudio': ['UObject'],
  'AFGWaterVolume': [
    "Unknown<'APhysicsVolume'>",
    'IFGExtractableResourceInterface',
    "Unknown<'IInterface_PostProcessVolume'>",
    "Unknown<'INavRelevantInterface'>",
    'IFGSignificanceInterface',
  ],
  'AFGWeaponAttachmentProjectile': ['AFGWeaponAttachment'],
  'AFGWeaponChild': ['AFGEquipmentChild'],
  'AFGWheeledVehicle': ['AFGVehicle'],
  'UFGWheeledVehicleMovementComponent4W': ["Unknown<'UWheeledVehicleMovementComponent4W'>"],
  'UFGWheeledVehicleMovementComponent6W': ["Unknown<'UWheeledVehicleMovementComponent'>"],
  'UFGWorkBench': ["Unknown<'USceneComponent'>", 'IFGRecipeProducerInterface'],
  'AFGWorldSettings': ["Unknown<'AWorldSettings'>", 'IFGSaveInterface'],
  'AFGAttachmentSplitterHologram': ['AFGConveyorAttachmentHologram'],
  'AFGBuildableHologram': ['AFGHologram'],
  'AFGBuildGuide': ['AActor'],
  'AFGConveyorAttachmentHologram': ['AFGFactoryHologram'],
  'AFGConveyorBeltHologram': ['AFGSplineHologram'],
  'AFGConveyorLiftHologram': ['AFGSplineHologram'],
  'AFGConveyorMultiPoleHologram': ['AFGBuildableHologram'],
  'AFGConveyorPoleHologram': ['AFGPoleHologram'],
  'AFGDecorHologram': ['AFGBuildableHologram'],
  'AFGFactoryBuildingHologram': ['AFGBuildableHologram'],
  'AFGFactoryHologram': ['AFGBuildableHologram'],
  'AFGFoundationHologram': ['AFGFactoryBuildingHologram'],
  'AFGGeoThermalGeneratorHologram': ['AFGResourceExtractorHologram'],
  'AFGHologram': ['AActor', 'IFGConstructionMessageInterface'],
  'AFGPipelineAttachmentHologram': ['AFGFactoryHologram'],
  'AFGPipelineHologram': ['AFGSplineHologram'],
  'AFGPipelineJunctionHologram': ['AFGPipelineAttachmentHologram'],
  'AFGPipelineSupportHologram': ['AFGFactoryHologram'],
  'AFGPipePartHologram': ['AFGFactoryHologram'],
  'AFGPipeReservoirHologram': ['AFGFactoryHologram'],
  'AFGPoleHologram': ['AFGFactoryHologram'],
  'AFGPoweredWallHologram': ['AFGWallHologram'],
  'AFGPowerPoleHologram': ['AFGBuildableHologram'],
  'AFGRailroadBridgeHologram': ['AFGSplineHologram'],
  'AFGRailroadTrackHologram': ['AFGSplineHologram'],
  'AFGRailroadVehicleHologram': ['AFGVehicleHologram'],
  'AFGResourceExtractorHologram': ['AFGFactoryHologram'],
  'AFGRoadHologram': ['AFGSplineHologram'],
  'AFGSpaceElevatorHologram': ['AFGFactoryHologram'],
  'AFGSplineHologram': ['AFGBuildableHologram'],
  'AFGStackableStorageHologram': ['AFGFactoryHologram'],
  'AFGStairHologram': ['AFGFoundationHologram'],
  'AFGStandaloneSignHologram': ['AFGBuildableHologram'],
  'AFGTradingPostHologram': ['AFGFactoryHologram'],
  'AFGTrainPlatformHologram': ['AFGFactoryHologram'],
  'AFGTrainStationHologram': ['AFGTrainPlatformHologram'],
  'AFGVehicleHologram': ['AFGHologram'],
  'AFGWalkwayHologram': ['AFGFactoryBuildingHologram'],
  'AFGWallAttachmentHologram': ['AFGBuildableHologram'],
  'AFGWallHologram': ['AFGFactoryBuildingHologram'],
  'AFGWheeledVehicleHologram': ['AFGVehicleHologram'],
  'AFGWireHologram': ['AFGBuildableHologram'],
  'UFGCollectionParamUniformFloat': ["Unknown<'UDistributionVector'>"],
  'AFGReplicationDetailActor_BuildableFactory': ['AFGReplicationDetailActor'],
  'AFGReplicationDetailActor_CargoPlatform': ['AFGReplicationDetailActor_BuildableFactory'],
  'AFGReplicationDetailActor_DockingStation': ['AFGReplicationDetailActor_BuildableFactory'],
  'AFGReplicationDetailActor_GeneratorFuel': ['AFGReplicationDetailActor_BuildableFactory'],
  'AFGReplicationDetailActor_GeneratorNuclear': ['AFGReplicationDetailActor_GeneratorFuel'],
  'AFGReplicationDetailActor_Manufacturing': ['AFGReplicationDetailActor_BuildableFactory'],
  'AFGReplicationDetailActor_Storage': ['AFGReplicationDetailActor_BuildableFactory'],
  'AFGReplicationDetailActor': ['AActor', 'IFGReplicationDependencyActorInterface'],
  'UFGReplicationDetailInventoryComponent': ["Unknown<'UActorComponent'>"],
  'UFGReplicationGraph': ["Unknown<'UReplicationGraph'>"],
  'UFGReplicationGraphNode_ConditionallyAlwaysRelevant': ["Unknown<'UReplicationGraphNode_ActorList'>"],
  'UFGReplicationGraphNode_AlwaysRelevant_ForConnection': [
    "Unknown<'UReplicationGraphNode_AlwaysRelevant_ForConnection'>",
  ],
  'UFGAnyUndefinedDescriptor': ['UFGItemDescriptor'],
  'UFGBuildDescriptor': ['UFGItemDescriptor'],
  'UFGBuildingDescriptor': ['UFGBuildDescriptor'],
  'UFGConsumableDescriptor': ['UFGEquipmentDescriptor'],
  'UFGDecorationDescriptor': ['UFGEquipmentDescriptor'],
  'UFGDecorDescriptor': ['UFGBuildingDescriptor'],
  'UFGEquipmentDescriptor': ['UFGItemDescriptor'],
  'UFGItemDescriptor': ['UObject'],
  'UFGItemDescriptorBiomass': ['UFGItemDescriptor'],
  'UFGItemDescriptorNuclearFuel': ['UFGItemDescriptor'],
  'UFGNoneDescriptor': ['UFGItemDescriptor'],
  'UFGPoleDescriptor': ['UFGBuildingDescriptor'],
  'AFGResourceDeposit': ['AFGResourceNode'],
  'UFGResourceDescriptor': ['UFGItemDescriptor'],
  'UFGResourceDescriptorGeyser': ['UFGResourceDescriptor'],
  'UFGUseState_NodeFullInventory': ['UFGUseState'],
  'UFGUseState_NonConveyorResource': ['UFGUseState'],
  'AFGResourceNode': [
    'AActor',
    'IFGExtractableResourceInterface',
    'IFGSaveInterface',
    'IFGUseableInterface',
    'IFGSignificanceInterface',
  ],
  'UFGVehicleDescriptor': ['UFGBuildDescriptor'],
  'UFGWildCardDescriptor': ['UFGItemDescriptor'],
  'AFGProfileSpline': ['AActor'],
  'UFGBaseUI': ["Unknown<'UUserWidget'>"],
  'UFGButtonWidget': ["Unknown<'UUserWidget'>"],
  'UFGCompassObjectWidget': ["Unknown<'UUserWidget'>"],
  'UFGCompassWidget': ["Unknown<'UUserWidget'>"],
  'UFGDynamicOptionsRow': ["Unknown<'UUserWidget'>"],
  'UFGGameUI': ['UFGBaseUI'],
  'UFGInteractWidget': ["Unknown<'UUserWidget'>"],
  'UFGListView': ["Unknown<'UPanelWidget'>"],
  'UFGListViewSlot': ["Unknown<'UPanelSlot'>"],
  'UFGManufacturingButton': ["Unknown<'UUserWidget'>"],
  'UFGMapObjectWidget': ["Unknown<'UUserWidget'>"],
  'UFGMapWidget': ["Unknown<'UUserWidget'>"],
  'UFGMenuBase': ["Unknown<'UUserWidget'>"],
  'UFGMultiplayerVerticalBox': ["Unknown<'UVerticalBox'>"],
  'UFGOptionsValueController': ["Unknown<'UUserWidget'>"],
  'UFGPopupWidget': ['UFGInteractWidget'],
  'UFGSignCanvasWidget': ["Unknown<'UUserWidget'>"],
  'UFGSignElementDragDrop': ["Unknown<'UDragDropOperation'>"],
  'UFGSignElementDragWidget': ["Unknown<'UUserWidget'>"],
  'UFGSignElementListWidget': ["Unknown<'UUserWidget'>"],
  'UFGSignElementSettingsWidget': ["Unknown<'UUserWidget'>"],
  'UFGSignElementWidget': ["Unknown<'UUserWidget'>"],
  'UFGSignInteractWidget': ['UFGInteractWidget'],
  'UFGSignTextWidget': ['UFGSignElementWidget'],
  'UFGTitleButton': ['UFGButtonWidget'],
  'UFGVirtualCursorFunctionLibrary': ["Unknown<'UBlueprintFunctionLibrary'>"],
  'UFGWidgetMultiplayer': ["Unknown<'UUserWidget'>"],
  'UFGWidgetSwitcher': ["Unknown<'UWidgetSwitcher'>"],
  'UFGWindow': ["Unknown<'UUserWidget'>"],
  'UFGAudioMessage': ['UFGMessageBase'],
  'UFGMessageBase': ["Unknown<'UUserWidget'>"],
  'UFGMessageSender': ['UObject'],
  'UFGUnlock': ['UObject'],
  'UFGUnlockArmEquipmentSlot': ['UFGUnlock'],
  'UFGUnlockBuildEfficiency': ['UFGUnlock'],
  'UFGUnlockBuildOverclock': ['UFGUnlock'],
  'UFGUnlockGiveItem': ['UFGUnlock'],
  'UFGUnlockInventorySlot': ['UFGUnlock'],
  'UFGUnlockMap': ['UFGUnlock'],
  'UFGUnlockRecipe': ['UFGUnlock'],
  'UFGUnlockScannableResource': ['UFGUnlock'],
  'UFGUnlockSchematic': ['UFGUnlock'],
  'FAnimInstanceProxyFactory': ["Unknown<'FAnimInstanceProxy'>"],
  'FFactoryTickFunction': ["Unknown<'FTickFunction'>"],
  'FFGAnimNode_RandomPlayer': ["Unknown<'FAnimNode_RandomPlayer'>"],
  'FRemovedInstance': ["Unknown<'FFastArraySerializerItem'>"],
  'FRemovedInstanceArray': ["Unknown<'FFastArraySerializer'>"],
  'FAnimInstanceProxyRailRoadVehicle': ["Unknown<'FAnimInstanceProxy'>"],
  'FResourceSinkRewardLevelsData': ["Unknown<'FTableRowBase'>"],
  'FResourceSinkPointsData': ["Unknown<'FTableRowBase'>"],
  'FSharedInventoryStatePtr': ["Unknown<'SharedPointerInternals::FReferenceControllerBase'>"],
};

